"""add attachment columns to tasks and checkins

Revision ID: 239277d719e6
Revises: 
Create Date: 2026-06-14 19:01:16.572757
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '239277d719e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('attachment_url', sa.Text(), nullable=True))
    op.add_column('checkins', sa.Column('attachment_name', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('attachment_url', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('attachment_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'attachment_name')
    op.drop_column('tasks', 'attachment_url')
    op.drop_column('checkins', 'attachment_name')
    op.drop_column('checkins', 'attachment_url')
    # ### end Alembic commands ###
